
server:
  port: 8081
  address: 192.168.0.108

spring:
  application:
  name: violet-sns
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns
    username: root
    password: root


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


violet:
  jwt:
    header: token
    expire: 604800
    secret: violetEvergarden

