server:
  port: 8081
  #address: 192.168.0.106
  #address: 192.168.107.60
spring:
  application:
  name: violet-sns
  redis:
    host: 192.168.153.131
    port: 6380
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.131:3306/sns #?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
violet:
  jwt:
    header: token
    expire: 86400
    secret: violetEvergarden
aliyun:
  oss:
    endpoint: https://cn-beijing.oss.aliyuncs.com
    bucketName: web-hqedu